### PR TITLE
changes for blender 3.6

### PR DESCRIPTION
**Pull request by arpit15**
- Applies c++ changes 
-  Requires c++17
- Add new way to create shaders in blender 3.6

### CODE REVIEW

**Comment by eliemichel** [comment]
Thanks a lot for this! May I ask in which context you got into studying/using DagAmendment? :)

**Comment by arpit15** [comment]
I have a CAD procedural way (using pygmsh) to generate shapes. Your hardops demo caught my eye. 
I wanted to checkout if I can allow automatic variation of my shape using your framework. 
However, I think the objectives of your work are different---you want to change things using 3D feedback instead of sliders, which is great. Since it doesn't allow for setting custom parameters in blender for shape variation, I am not using it going forward.

**Comment by eliemichel** [comment]
Thanks for your feedback! What do you mean by setting custom parameters in blender? I don't know gmsh, does it provide access to the construction tree, and do the operation support corner attribtue forwarding (e.g., preserving UV texture coordinates)?

**Comment by arpit15** [comment]
`gmsh` is B-rep based [CAD tool](https://gmsh.info/). I can write a script with parameters to generate shapes. By custom parameters, I meant to refer to the parameters of my script. 
For ex: I can write a script to create a b-spline curve and extrude it to create a surface. I want to be able to change the extrude length or b-spline control points in blender without resorting to gmsh. 
According to my knowledge, B-rep based methods are different than CSG-based methods for shape generation. So, gmsh can potentially output a graph of operations but I am unsure about corner attribute forwarding.

**Pull request merged**
